ViewModels/InformationViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LineOfficial_MVC.ViewModels
{
    /// <summary>
    /// 商家資訊 ViewModel
    /// </summary>
    public class InformationViewModel : BaseViewModel
    {
        
    }
}

ViewModels/QuestionChatBoxViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LineOfficial_MVC.ViewModels
{
    /// <summary>
    /// 聊天室回覆ViewModel
    /// </summary>
    public class QuestionChatBoxViewModel : BaseViewModel
    {
        public QuestionChatBoxViewModel()
        {
            QuestionNo = string.Empty;
            Message = string.Empty;
        }

        public string QuestionNo { get; set; }

        /// <summary>
        /// 問題內容
        /// </summary>
        [Required(ErrorMessage = "必填")]
        public string Message { get; set; }
    }
}

ViewModels/QuestionListViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LineOfficial_MVC.ViewModels
{
    /// <summary>
    /// 歷史訊息列表ViewModel
    /// </summary>
    public class QuestionListViewModel : BaseViewModel
    {
    }
}

ViewModels/QuestionViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LineOfficial_MVC.ViewModels
{
    /// <summary>
    /// 提問ViewModel
    /// </summary>
    public class QuestionViewModel : BaseViewModel
    {
        public QuestionViewModel()
        {
            Message = string.Empty;
            QuestionTypeSelectList = new();
        }
        /// <summary>
        /// 問題類別ID
        /// </summary>
        public int QuestionTypeID { get; set; }
        /// <summary>
        /// 問題內容
        /// </summary>
        [Required(ErrorMessage = "必填")]
        public string Message { get; set; }
        /// <summary>
        /// 問題下拉選單列表
        /// </summary>
        public List<QuestionTypeModel> QuestionTypeSelectList { get; set; }
    }

    /// <summary>
    /// 問題下拉選單物件
    /// </summary>
    public class QuestionTypeModel
    {
        public QuestionTypeModel()
        {
            TypeName = string.Empty;
        }
        public int TypeID { get; set;}
        public string TypeName { get; set; }
    }
}

ViewModels/UploadViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace LineOfficial_MVC.ViewModels
{
    /// <summary>
    /// 上傳ViewModel
    /// </summary>
    public class UploadViewModel : BaseViewModel
    {
        
    }
}

Controllers/LiffController.cs
using LineOfficial_MVC.Models;
using LineOfficial_MVC.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Data;

namespace LineOfficial_MVC.Controllers
{
    public class LiffController : Controller
    {
        private readonly ILogger<LiffController> _logger;

        /// <summary>
        /// 建構子
        /// </summary>
        public LiffController(ILogger<LiffController> logger)
        {
            _logger = logger;
        }

        #region 綁定功能
        /// <summary>
        /// Line liff 綁定頁
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index()
        {
            IndexViewModel model = new IndexViewModel();

            try
            {
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            return View(model);
        }

        /// <summary>
        /// 商家Line帳號綁定SCM帳號 (LineBotUserID 綁定)
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult BindAccount([FromForm] IndexViewModel data)
        {
            ResponseModel<string> response = new ResponseModel<string>();

            try
            {
                response.Message = $"已綁定所屬商家：{data.CustomerNum}";
                response.Success = true;

                //設定跳轉商家資訊業面連結 (只能使用liff網址)
                //response.Data = "/liff/information";
                response.Data = "https://liff.line.me/1661441976-ZJrQ1aqK";
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            return Json(response);
        }
        #endregion

        #region 商家資訊功能
        /// <summary>
        /// Line liff 商家資訊頁
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Information()
        {
            return View();
        }
        #endregion

        #region 資料下載功能
        /// <summary>
        /// Line liff 資料下載頁
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Download()
        {
            return View();
        }
        #endregion

        #region 資料上傳功能
        /// <summary>
        /// Line liff 資料上傳頁
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Upload()
        {
            return View();
        }
        #endregion

        #region 提問功能
        /// <summary>
        /// Line liff 提問頁
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Question()
        {
            QuestionViewModel model = new QuestionViewModel();

            try
            {
                //建立問題類別
                List<QuestionTypeModel> questionTypes = new List<QuestionTypeModel>();
                questionTypes.Add(new QuestionTypeModel { TypeID = 2, TypeName = "出貨", });
                questionTypes.Add(new QuestionTypeModel { TypeID = 1, TypeName = "訂單", });
                questionTypes.Add(new QuestionTypeModel { TypeID = 0, TypeName = "其他", });

                model.QuestionTypeSelectList = questionTypes;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            return View(model);
        }

        /// <summary>
        /// 提問送出
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult QuestionSend([FromForm] QuestionViewModel data)
        {
            ResponseModel response = new ResponseModel();

            try
            {
                response.Message = $"已收到您({data.LineBotUserID})的提問：{data.Message}";
                response.Success = true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }
            
            return Json(response);
        }
        #endregion

        #region 歷史問題功能
        /// <summary>
        /// Line liff 歷史問題列表頁面
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult QuestionList(string userid = "")
        {
            QuestionListViewModel model = new QuestionListViewModel();

            if (!string.IsNullOrEmpty(userid))
            {
                model.LineBotUserID = userid;
            }

            return View(model);
        }

        /// <summary>
        /// 結案
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult FinishQuestion(string userId, string questionNo)
        {
            ResponseModel response = new ResponseModel();

            try
            {
                response.Message = $"您({userId})已將({questionNo}0結案";
                response.Success = true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            return Json(response);
        }

        /// <summary>
        /// Line liff 進入歷史問題聊天室
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult QuestionChatBox(string questionNo, string userId = "")
        {
            QuestionChatBoxViewModel model = new QuestionChatBoxViewModel();

            try
            {
                //設定UserID
                model.LineBotUserID = userId;
                //設定QuestionNo
                model.QuestionNo = questionNo;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            return View(model);
        }

        /// <summary>
        /// 聊天室 上傳檔案 Modal
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult UploadFileModal()
        {
            return PartialView("_questionDetailUploadModal");
        }

        /// <summary>
        /// 回覆聊天室
        /// </summary>
        /// <param name="data"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult QuestionChatBoxReply([FromForm] QuestionChatBoxViewModel data)
        {
            ResponseModel response = new ResponseModel();

            try
            {
                response.Message = $"已收到您({data.LineBotUserID})的回覆：{data.Message}";
                response.Success = true;
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            return Json(response);
        }
        #endregion


        /// <summary>
        /// Line liff 綁定頁
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Index2()
        {

            try
            {
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
            }

            return View();
        }

    }
}

Views/Liff/Download.cshtml
@{
    ViewBag.Title = "台灣好農SCM LINE::檔案下載";
    @section Scripts{
        <script type="text/javascript" src="~/js/views/download.js" asp-append-version="true"></script>
    }
}

<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="download">檔案下載</h2>
        @*LineBotUserID*@
        <h3 id="userIdtext">No UserID</h3>

        <div class="items">
            <ul>
                <li>
                    <div class="items-form">
                        <div class="file-download type-pdf">商品規格書.pdf</div>
                    </div>
                </li>
                @*<li>
                    <div class="items-form">
                        <div class="file-download type-jpg">商品規格書.jpg</div>
                    </div>
                </li>
                <li>
                    <div class="items-form">
                        <div class="file-download type-word">商品規格書.word</div>
                    </div>
                </li>
                <li>
                    <div class="items-form">
                        <div class="file-download type-file">商品規格書.file</div>
                    </div>
                </li>*@
            </ul>
            <div class="btn"><a href="javascript:;">下載</a></div>
        </div>
    </div>
</div>

Views/Liff/Index.cshtml
@model LineOfficial_MVC.ViewModels.IndexViewModel
@{
    ViewBag.Title = "台灣好農SCM LINE::帳號綁定";
    @section Scripts{
        <script type="text/javascript" src="~/js/views/index.js" asp-append-version="true"></script>
    }
}

<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png?v=1.0" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="bind">商家帳號綁定</h2>
        @*UserID*@
        <h3 id="userIdtext">No UserID</h3>
        @*UserName*@
        <h3 id="userNametext">No UserName</h3>
        @*UserEmail*@
        <h3 id="userEmailtext">No UserEmail</h3>

        <a asp-controller="Liff" asp-action="Index2">跳轉Index2</a>

        <form id="formBindAccount" asp-controller="Liff" asp-action="BindAccount" method="post" enctype="multipart/form-data">
            <div class="items">
                <ul>
                    @*hidden UserID*@
                    <input type="hidden" id="userId" asp-for="@Model.LineBotUserID" />
                    @*hidden UserName*@
                    <input type="hidden" id="userName" asp-for="@Model.CustomerAccountName" />
                    @*hidden userEmail*@
                    <input type="hidden" id="userEmail" asp-for="@Model.CustomerAccountEmail" />

                    <li>
                        <div class="items-title">商家編號：</div>
                        <div class="items-form">
                            <span asp-validation-for="@Model.CustomerNum" class="text-danger"></span>
                            <input type="text" asp-for="@Model.CustomerNum">
                        </div>
                    </li>
                </ul>
                <div class="btn"><a class="save-button" href="javascript:;">綁定</a></div>
            </div>
        </form>
    </div>
</div>

Views/Liff/Index2.cshtml
<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png?v=1.0" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="bind">跳轉成功</h2>
        
    </div>
</div>

Views/Liff/Information.cshtml
@model LineOfficial_MVC.ViewModels.InformationViewModel
@{
    ViewBag.Title = "台灣好農SCM LINE::商家資訊";
    @section Scripts{
        <script type="text/javascript" src="~/js/views/information.js" asp-append-version="true"></script>
    }
}

<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="info">商家資訊</h2>
        @*UserID*@
        <h3 id="userIdtext">No UserID</h3>
        <div class="items info-items">
            <ul>
                <li>
                    <div class="items-title">商家編號：</div>
                    <div class="items-content">H2019102500028</div>
                </li>
                <li>
                    <div class="items-title">商家名稱：</div>
                    <div class="items-content">米家樂有機農場</div>
                </li>
                <li>
                    <div class="items-title">綁定狀態：</div>
                    <div class="items-content">已申請綁定</div>
                </li>
            </ul>
            <div class="btn"><a href="javascript:;" id="close">返回</a></div>
        </div>
    </div>
</div>

Views/Liff/Question.cshtml
@model LineOfficial_MVC.ViewModels.QuestionViewModel
@{
    ViewBag.Title = "台灣好農SCM LINE::問題詢問";
    @section Scripts{
        <script type="text/javascript" src="~/js/views/question.js" asp-append-version="true"></script>
    }
}

<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="question">問題詢問</h2>
        @*LineBotUserID*@
        <h3 id="userIdtext">No UserID</h3>

        <div class="items">
            <form id="formQuestion" asp-controller="Liff" asp-action="QuestionSend" method="post" enctype="multipart/form-data">
                @*hidden LineBotUserID*@
                <input type="hidden" id="userId" asp-for="@Model.LineBotUserID" />

                <ul>
                    <li>
                        <div class="items-title">問題類別：</div>
                        <div class="items-form">
                            <select asp-for="@Model.QuestionTypeID">
                                @foreach (var item in @Model.QuestionTypeSelectList)
                                {
                                    <option value="@item.TypeID">@item.TypeName</option>
                                }
                            </select>
                        </div>
                    </li>
                    <li>
                        <div class="items-title">問題描述：</div>
                        <div class="items-form">
                            <span asp-validation-for="@Model.Message" class="text-danger"></span>
                            <textarea placeholder="請輸入您的提問" asp-for="@Model.Message"></textarea>
                        </div>
                    </li>
                    <li>
                        <div class="items-title">上傳檔案：</div>
                        <div class="items-form"><input class="upload-file" type="file" accept=".jpg, .png, .gif, .bmp, .doc, .docx, .xls, .pdf, .ppt"></div>
                        <div class="items-form"><input class="upload-file" type="file" accept=".jpg, .png, .gif, .bmp, .doc, .docx, .xls, .pdf, .ppt"></div>
                        <div class="items-form"><input class="upload-file" type="file" accept=".jpg, .png, .gif, .bmp, .doc, .docx, .xls, .pdf, .ppt"></div>
                        <div class="notice">
                            檔案大小限制：5MB；支援jpg、png、gif、bmp、doc、docx、xls、pdf、ppt
                        </div>
                    </li>
                </ul>
                <div class="btn"><a class="save-button" href="javascript:;">送出</a></div>
            </form>
        </div>
    </div>
</div>

Views/Liff/QuestionChatBox.cshtml
@model LineOfficial_MVC.ViewModels.QuestionChatBoxViewModel
@{
    ViewBag.Title = "台灣好農SCM LINE::問題內容";
    @section Scripts{
        <script type="text/javascript" src="~/js/views/questionchatbox.js" asp-append-version="true"></script>
    }
}

<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="question">問題內容</h2>
        @*UserID*@
        <p>@Model.LineBotUserID</p>
        @*hidden UserID*@
        <input type="hidden" id="userId" asp-for="@Model.LineBotUserID" />
        @*QuestionNo*@
        <p>@Model.QuestionNo</p>

        <div class="message-wrap">
            <div class="question-wrap">
                <div class="item-set">
                    <div class="user-name que">George</div>
                    <div class="question-item">
                        <p>為什麼我訂購的商品沒有一次抵達?</p>
                        <div class="attach-question"><a href="javascript:;">附件</a></div>
                        <div class="question-time">2023-08-22 14:45</div>
                    </div>
                </div>
                <div class="item-set">
                    <div class="user-name ans">Alice</div>
                    <div class="answer-item">
                        <p>
                            由於不同的商品性質，可能會分為由產地或者店家直接出貨，例如整箱同品項的商品(整箱水果、整箱根莖等)；也可能會由倉庫集合整理後出貨，例如單份購買之商品或者食材箱等，因此您可能會分次收到來自全台各地寄出的農產品。
                        </p>
                        <div class="attach-question"><a href="javascript:;">附件</a></div>
                        <div class="question-time">2023-08-22 14:45</div>
                    </div>
                </div>
                <div class="item-set">
                    <div class="user-name quest">George</div>
                    <div class="question-item">
                        <p>請問可以預定到貨日期嗎?</p>
                        <div class="question-time">2023-08-22 14:45</div>
                    </div>
                </div>
                <div class="item-set">
                    <div class="user-name ans">Alice</div>
                    <div class="answer-item">
                        <p>不可以哦。</p>
                        <div class="question-time">2023-08-22 14:45</div>
                    </div>
                </div>
            </div>

            @* 回覆表單 *@
            <form id="formQuestionChatBoxReply" asp-controller="Liff" asp-action="QuestionChatBoxReply" method="post" enctype="multipart/form-data">
                <div class="reply-box">
                    @*hidden UserID*@
                    <input type="hidden" asp-for="@Model.LineBotUserID" />
                    @*hidden QuestionNo*@
                    <input type="hidden" asp-for="@Model.QuestionNo" />

                    <div class="message">
                        <span asp-validation-for="@Model.Message" class="text-danger" style="color:red"></span>
                        <textarea placeholder="輸入訊息" asp-for="@Model.Message"></textarea>
                    </div>
                    <div class="submit-box">
                        @* 附件按鈕 *@
                        <div class="btn paperclip">
                            <a class="upload_item" asp-action="UploadFileModal" asp-controller="Liff">附件</a>
                        </div>
                        <input id="file1" name="File1" type="file" style="display:none">
                        <input id="file2" name="File2" type="file" style="display:none">
                        <input id="file3" name="File3" type="file" style="display:none">
                        <div class="files-box">
                            <ul>
                                <li><img src="~/images/file.png" width="28" height="28" alt="" /></li>
                                <li><img src="~/images/file-jpg.png" width="28" height="28" alt="" /></li>
                                <li><img src="~/images/file-pdf.png" width="28" height="28" alt="" /></li>
                            </ul>
                        </div>
                        <div class="btn submit"><a class="save-button" href="javascript:;">送出</a></div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

Views/Liff/QuestionList.cshtml
@model LineOfficial_MVC.ViewModels.QuestionListViewModel

@{
    ViewBag.Title = "台灣好農SCM LINE::問題清單";
    @section Scripts{
        <script type="text/javascript" src="~/js/views/questionlist.js" asp-append-version="true"></script>
    }
}

<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="question">問題清單</h2>

        @*UserID*@
        <h3>@Model.LineBotUserID</h3>

        <div class="items question-items">
            @*hidden UserID*@
            <input type="hidden" asp-for="@Model.LineBotUserID" />

            <ul>
                <li>
                    <div class="items-title">問題類別：</div>
                    <div class="items-content">註冊問題</div>
                </li>
                <li>
                    <div class="items-title">問題描述：</div>
                    <div class="items-content column-set">為什麼我訂購同一筆訂單的商品宅配分了很多批抵達是否有集運的功能?</div>
                </li>
                <li>
                    <div class="items-title">詢問日期：</div>
                    <div class="items-content">2023-08-22</div>
                </li>
                <li>
                    <div class="items-title">狀態：</div>
                    <div class="items-content">未結案</div>
                </li>
                <li>
                    <div class="items-content">
                        <div class="btn">
                            <a class="reply_item"
                               href="https://liff.line.me/1661441976-vnGLKdyP"
                               data-userid="@Model.LineBotUserID"
                               data-questionno="85a08227-35c2-85a4-2e70-f3d8e2206d93">
                                詳細
                            </a>
                            <a class="finish_item"
                               href="@Url.Action("FinishQuestion", "Liff")"
                               data-userid="@Model.LineBotUserID"
                               data-questionno="85a08227-35c2-85a4-2e70-f3d8e2206d93">
                                結案
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="btn"><a id="close" href="javascript:;">返回</a></div>
    </div>
</div>

Views/Liff/Upload.cshtml
@model LineOfficial_MVC.ViewModels.UploadViewModel
@{
    ViewBag.Title = "台灣好農SCM LINE::檔案上傳";
    @section Scripts{
        <script type="text/javascript" src="~/js/views/upload.js" asp-append-version="true"></script>
    }
}

<div class="main">
    <div class="main-box">
        <div class="logo"><img src="~/images/logo.png" alt="" /></div>
        <div class="logo-word">台灣好農</div>
        <div class="logo-word-en">The Wonderfulfood</div>
        <h2 class="upload">檔案上傳</h2>
        @*UserID*@
        <h3 id="userIdtext">No UserID</h3>

        <form id="FileUpload" asp-controller="Liff" asp-action="FileUpload" method="post" enctype="multipart/form-data">
            <div class="items">
                <ul>
                    @*hidden UserID*@
                    <input type="hidden" id="userId" asp-for="@Model.LineBotUserID" />

                    <li>
                        <div class="items-title">選擇檔案：</div>
                        <div class="items-form"><input type="file" class="upload-file" accept=".jpg, .png, .gif, .bmp, .doc, .docx, .xls, .pdf, .ppt"></div>
                        <div class="notice">檔案大小限制：5MB；支援jpg、png、gif、bmp、doc、docx、xls、pdf、ppt</div>
                    </li>
                </ul>
                <div class="btn"><a class="save-button" href="javascript:;">上傳</a></div>
            </div>
        </form>
    </div>
</div>

Views/Liff/_questionDetailUploadModal.cshtml
@* 聊天室上傳檔案 Modal *@
<div class="bg_close" onclick="closeModal()"></div>
<div id="uploadFileModal" class="w3-modal-content w3-animate-top w3-card-4 modal_box">
    <span onclick="closeModal()" class="w3-button w3-display-topright">&times;</span>
    <div class="message_box">
        <div class="attachment">
            <div class="items-title">附件：</div>
            <ul>
                <li>
                    <input id="uploadFile1" type="file" class="upload-file" placeholder="附件" accept=".jpg, .png, .gif, .bmp, .doc, .docx, .xls, .pdf, .ppt">
                    <div class="dismiss"><a onclick='javascript: cancelFile("#uploadFile1");' href="javascript:;"><img src="~/images/clear.png" alt="" /></a></div>
                </li>
                <li>
                    <input id="uploadFile2" type="file" class="upload-file" placeholder="附件" accept=".jpg, .png, .gif, .bmp, .doc, .docx, .xls, .pdf, .ppt">
                    <div class="dismiss"><a onclick='javascript: cancelFile("#uploadFile2");' href="javascript:;"><img src="~/images/clear.png" alt="" /></a></div>
                </li>
                <li>
                    <input id="uploadFile3" type="file" class="upload-file" placeholder="附件" accept=".jpg, .png, .gif, .bmp, .doc, .docx, .xls, .pdf, .ppt">
                    <div class="dismiss"><a onclick='javascript: cancelFile("#uploadFile3");' href="javascript:;"><img src="~/images/clear.png" alt="" /></a></div>
                </li>
            </ul>
        </div>
        <div class="notice">檔案大小限制：5MB；支援jpg、png、gif、bmp、doc、docx、xls、pdf、ppt</div>
        <div class="btn"><a class="upload-button" href="javascript:;">確定</a></div>
    </div>
</div>